export const CHANGE_INPUT_VALUE = 'change_input_value'
export const ADD_LIST_VALUE = 'add_list_value'
export const DELETE_LIST_VALUE = 'delete_list_value'
export const INIT_LIST = 'init_list'
export const GET_INIT_LIST = 'get_init_list'
